apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-myapp-config
  namespace: {{.Values.namespace}}
data:
  HELLO: {{.Values.dataHello}}
  API_PREFIX: {{.Values.apiPrefix}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-myapp
  namespace: {{.Values.namespace}}
  labels:
    app: hello-myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-myapp
  template:
    metadata:
      labels:
        app: hello-myapp
    spec:
      containers:
      - name: hello-myapp
        image: hello
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: HELLO
          valueFrom:
            configMapKeyRef:
              name: hello-myapp-config
              key: HELLO
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              name: hello-myapp-config
              key: API_PREFIX
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: hello-myapp-service
spec:
  selector:
    app: hello-myapp
  type: LoadBalancer
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 8000
    nodePort: {{.Values.nodePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-myapp-ingress
  namespace: {{.Values.namespace}}
  labels:
    name: hello-myapp-ingress
spec:
  rules:
  - host: api.yay.com
    http:
      paths:
      - pathType: Prefix
        path: {{.Values.apiPrefix}} 
        backend:
          service:
            name: hello-myapp-service
            port: 
              number: 9999
